package com.github.javaparser.symbolsolver;

import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.expr.NameExpr;
import com.github.javaparser.resolution.declarations.ResolvedValueDeclaration;
import com.github.javaparser.symbolsolver.resolution.AbstractResolutionTest;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;
import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * The processing type parsing is slow. The statement for obtaining the value assignment in BlockStmtContext uses two loops. As a result, the time complexity is n x n.
 */
public class Issue3181Test extends AbstractResolutionTest {

    @Test
    public void test() throws IOException {
        String code = "public class HTMLSchema {\n" +
                "\tpublic static final int M_INLINE = 1 << 12;\n" +
                "\tpublic static final int M_NOLINK = 1 << 15;\n" +
                "\tpublic void attribute(String elemName, String attrName, String type, String value) {\n" +
                "\t}\n" +
                "\n" +
                "\tpublic HTMLSchema() {\n" +
                "\t\telementType(\"<pcdata>\", M_NOLINK, M_NOLINK, 0);\n" +
                "\t\telementType(\"<root>\", M_NOLINK, M_NOLINK, 0);\n" +
                "\t\telementType(\"a\", M_NOLINK|M_NOLINK, M_INLINE, 0);\n" +
                "\t\telementType(\"abbr\", M_NOLINK|M_INLINE, M_INLINE|M_NOLINK, M_NOLINK);\n" +
                "\t\telementType(\"acronym\", M_NOLINK|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE|M_INLINE, M_INLINE|M_NOLINK, M_NOLINK);\n" +
                "\t\tattribute(\"a\", \"hreflang\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"shape\", \"CDATA\", \"rect\");\n" +
                "\t\tattribute(\"a\", \"tabindex\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"nohref\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"area\", \"shape\", \"CDATA\", \"rect\");\n" +
                "\t\tattribute(\"area\", \"tabindex\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"clear\", \"CDATA\", \"none\");\n" +
                "\t\tattribute(\"button\", \"disabled\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"button\", \"tabindex\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"type\", \"CDATA\", \"submit\");\n" +
                "\t\tattribute(\"caption\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"span\", \"CDATA\", \"1\");\n" +
                "\t\tattribute(\"col\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"span\", \"CDATA\", \"1\");\n" +
                "\t\tattribute(\"colgroup\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"div\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"form\", \"enctype\", \"CDATA\", \"application/x-www-form-urlencoded\");\n" +
                "\t\tattribute(\"form\", \"method\", \"CDATA\", \"get\");\n" +
                "\t\tattribute(\"frame\", \"frameborder\", \"CDATA\", \"1\");\n" +
                "\t\tattribute(\"frame\", \"noresize\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"frame\", \"scrolling\", \"CDATA\", \"auto\");\n" +
                "\t\tattribute(\"h1\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"h2\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"h3\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"h4\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"h5\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"h6\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"hr\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"hr\", \"noshade\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"iframe\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"iframe\", \"frameborder\", \"CDATA\", \"1\");\n" +
                "\t\tattribute(\"iframe\", \"scrolling\", \"CDATA\", \"auto\");\n" +
                "\t\tattribute(\"img\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"img\", \"ismap\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"input\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"input\", \"checked\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"input\", \"disabled\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"input\", \"ismap\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"input\", \"maxlength\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"input\", \"readonly\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"input\", \"tabindex\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"input\", \"type\", \"CDATA\", \"text\");\n" +
                "\t\tattribute(\"label\", \"for\", \"IDREF\", null);\n" +
                "\t\tattribute(\"legend\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"li\", \"value\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"link\", \"hreflang\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"marquee\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"menu\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"meta\", \"http-equiv\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"meta\", \"name\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"object\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"object\", \"declare\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"object\", \"tabindex\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ol\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ol\", \"start\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"optgroup\", \"disabled\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"option\", \"disabled\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"option\", \"selected\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"p\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"param\", \"valuetype\", \"CDATA\", \"data\");\n" +
                "\t\tattribute(\"pre\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"rt\", \"rbspan\", \"CDATA\", \"1\");\n" +
                "\t\tattribute(\"script\", \"defer\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"select\", \"disabled\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"select\", \"multiple\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"select\", \"size\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"select\", \"tabindex\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"table\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"table\", \"frame\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"table\", \"rules\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tbody\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tbody\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"td\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"td\", \"colspan\", \"CDATA\", \"1\");\n" +
                "\t\tattribute(\"td\", \"headers\", \"IDREFS\", null);\n" +
                "\t\tattribute(\"td\", \"nowrap\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"td\", \"rowspan\", \"CDATA\", \"1\");\n" +
                "\t\tattribute(\"td\", \"scope\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"td\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"textarea\", \"cols\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"textarea\", \"disabled\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"textarea\", \"readonly\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"textarea\", \"rows\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"textarea\", \"tabindex\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tfoot\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tfoot\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"th\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"th\", \"colspan\", \"CDATA\", \"1\");\n" +
                "\t\tattribute(\"th\", \"headers\", \"IDREFS\", null);\n" +
                "\t\tattribute(\"th\", \"nowrap\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"th\", \"rowspan\", \"CDATA\", \"1\");\n" +
                "\t\tattribute(\"th\", \"scope\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"th\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"thead\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"thead\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"em\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"em\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"em\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"th\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"th\", \"colspan\", \"CDATA\", \"1\");\n" +
                "\t\tattribute(\"th\", \"headers\", \"IDREFS\", null);\n" +
                "\t\tattribute(\"th\", \"nowrap\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"th\", \"rowspan\", \"CDATA\", \"1\");\n" +
                "\t\tattribute(\"th\", \"scope\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"th\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"thead\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"thead\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"em\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"em\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"em\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"th\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"th\", \"colspan\", \"CDATA\", \"1\");\n" +
                "\t\tattribute(\"th\", \"headers\", \"IDREFS\", null);\n" +
                "\t\tattribute(\"th\", \"nowrap\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"th\", \"rowspan\", \"CDATA\", \"1\");\n" +
                "\t\tattribute(\"th\", \"scope\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"th\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"thead\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"thead\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"em\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"em\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"em\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"th\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"th\", \"colspan\", \"CDATA\", \"1\");\n" +
                "\t\tattribute(\"th\", \"headers\", \"IDREFS\", null);\n" +
                "\t\tattribute(\"th\", \"nowrap\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"th\", \"rowspan\", \"CDATA\", \"1\");\n" +
                "\t\tattribute(\"th\", \"scope\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"th\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"thead\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"thead\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"em\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"em\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"em\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"th\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"th\", \"colspan\", \"CDATA\", \"1\");\n" +
                "\t\tattribute(\"th\", \"headers\", \"IDREFS\", null);\n" +
                "\t\tattribute(\"th\", \"nowrap\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"th\", \"rowspan\", \"CDATA\", \"1\");\n" +
                "\t\tattribute(\"th\", \"scope\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"th\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"thead\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"thead\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"em\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"em\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"em\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"th\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"th\", \"colspan\", \"CDATA\", \"1\");\n" +
                "\t\tattribute(\"th\", \"headers\", \"IDREFS\", null);\n" +
                "\t\tattribute(\"th\", \"nowrap\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"th\", \"rowspan\", \"CDATA\", \"1\");\n" +
                "\t\tattribute(\"th\", \"scope\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"th\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"thead\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"thead\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"align\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"em\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"em\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"em\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"tr\", \"valign\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"ul\", \"compact\", \"BOOLEAN\", null);\n" +
                "\t\tattribute(\"ul\", \"type\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"xmp\", \"width\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"a\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"abbr\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"acronym\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"address\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"applet\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"area\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"b\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"base\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"basefont\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bdo\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"bgsound\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"big\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blink\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"blockquote\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"body\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"br\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"button\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"canvas\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"caption\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"center\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"cite\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"code\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"col\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"colgroup\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"comment\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dd\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"del\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dfn\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dir\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"div\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dl\", \"class\", \"NMTOKEN\", null);\n" +
                "\t\tattribute(\"dt\", \"class\", \"NMTOKEN\", null);\n" +
                "\t}\n" +
                "\n" +
                "\n" +
                "\tpublic void elementType(String name, int model, int memberOf, int flags) {\n" +
                "\n" +
                "\t}\n" +
                "}";
        
        ParserConfiguration config = new ParserConfiguration();
        config.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver(false)));
        StaticJavaParser.setConfiguration(config);

        CompilationUnit cu = StaticJavaParser.parse(code);
        cu.findAll(MethodCallExpr.class).forEach(methodCallExpr -> {
            if (methodCallExpr.toString().contains("elementType")) {
                Long time = System.currentTimeMillis();
                methodCallExpr.resolve();
                System.out.println((System.currentTimeMillis() - time) + ":" + methodCallExpr.toString());
            }
        });
    }

}
